#!/bin/bash
#PBS -l nodes=r23i13n23:ppn=3
#PBS -W group_list=lees_swm_ls_ext
#PBS -l pmem=5gb
#PBS -A lp_ees_swm_ls_001
#PBS -l walltime=24:00:00
#PBS -m abe
#PBS -M alexander.gruber@kuleuven.be
#PBS -o ./log.txt
#PBS -e ./out.txt

cd $PBS_O_WORKDIR

python reformat_SMOS_IC.py

ncks -4 -L 4 --cnk_dmn time,30000 --cnk_dmn lat,1 --cnk_dmn lon,1 SMOS_IC_images.nc SMOS_IC_timeseries.nc

cd $PBS_O_WORKDIR
rm -f out.txt log.txt